name: 定时创建命令

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
jobs:
  create-pr:
    runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Create Branch
            uses: actions/github-script@v7
            with:
            script: |
              const octokit = github.getOctokit(${{ secrets.GITHUB_TOKEN }});
              const { owner, repo } = context.repo;
              const curDate = +new Date()
              const branchName = `feature/${curDate}/auto-create`;
              const baseRef = 'main';
              
              await octokit.rest.git.createRef({
                owner,
                repo,
                ref: `refs/heads/${branchName}`,
                sha: context.sha
              });


